### ISSUE TITLE
Re: pre0.99.20-177: Updated copyright year

### ISSUE THREAD

**Issue by kseistrup** [jedsoft/jed#3]
E.g. `vmshelp.c` now has:

```c
/* Copyright (c) 1992-2023 John E. Davis
```

Matija Šuklje argues that all that is necessary is:

```c
© {$year_of_file_creation} {$name_of_copyright_holder} <{$contact}>
```

Source of information:

* https://matija.suklje.name/how-and-why-to-properly-write-copyright-statements-in-your-code

**Comment by jedsoft** [comment]
Thanks for pointing me to the article.  A few years ago I did a web
search on the matter and opinions were all over the place.  So to
cover all the bases I started to use a range.  I will try to refrain
updating the year in the future, except on the messages that appear at
start-up, since I think that having the release year conveys useful
information.  With that said, the version of jed on github has 2022
copyrights but the version on git.jedsoft.org has 2023.  When I next push
to github, the files will update to 2023 also.

Thanks,
--John

On Wed, 04 Jan 2023 04:03:29 -0800, Klaus Alexander Seiﬆrup ***@***.***> said:
>E.g. `vmshelp.c` now has:
>
>```c
>/* Copyright (c) 1992-2023 John E. Davis
>```
>
>Matija Å uklje argues that all that is necessary is:
>
>```c
>Â© {$year_of_file_creation} {$name_of_copyright_holder} <{$contact}>
>```
>
>Source of information:
>
>* https://matija.suklje.name/how-and-why-to-properly-write-copyright-stateme
>nts-in-your-code
